[package]
name = "tmc5160"
version = "0.0.1"
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
authors = ["Boris Vinogradov <no111u3@gmail.com>", "Linus Leo Stöckli <https://github.com/hacknus>"]
description = "A platform agnostic TMC5160 Trinamic integrated stepper motor controller"
edition = "2021"
keywords = ["embedded-hal-driver", "motor-controller", "stepper", "tmc5160"]
repository = "https://github.com/no111u3/tmc5160"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
#modular-bitfield = "0.13.1"
# need a version with `defmt` support.
modular-bitfield = { git = "https://github.com/makerpnp/modular-bitfield", rev = "db61b82052990068f32f59d3ed187647159556db", features = ["defmt"] }
#modular-bitfield = { path = "../modular-bitfield", features = ["defmt"] }
modular-bitfield-to-value = { git = "https://github.com/makerpnp/modular-bitfield-to-value", branch = "makerpnp" }
#modular-bitfield-to-value = { path = "../modular-bitfield-to-value" }
defmt = { version = "1.0.1", optional = true }

[dependencies.embedded-hal]
version = "1.0.0"

[features]
default = ["defmt"]
std = []
defmt = [
    "modular-bitfield/defmt",
    "dep:defmt",
]

[profile.dev]
incremental = false
codegen-units = 1

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
